import = ["/home/sam/.config/alacritty/colors.toml", "/home/sam/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true
history = 10000
multiplier = 3
opacity = 0.85
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 12
y = 12
