[files]
recent_files=/home/sam/Downloads/and.cct;/home/sam/Downloads/startlogsim.bat;/home/sam/Downloads/week5.cct;/home/sam/.config/openbox/rc.xml;/home/sam/.config/picom.conf;/home/sam/Downloads/zshrc;
recent_projects=
current_page=1
FILE_NAME_0=569;None;0;EUTF-8;1;1;0;%2Fhome%2Fsam%2FDownloads%2Fweek5.cct;0;4
FILE_NAME_1=24;None;0;EUTF-8;1;1;0;%2Fhome%2Fsam%2FDownloads%2Fand.cct;0;4

[project]
session_file=
project_file_path=

[geany]
treeview_position=156
msgwindow_position=472
geometry=688;405;664;349;0;
sidebar_page=0

[VTE]
last_dir=/home/sam/Downloads

[search]
find_all_expanded=false
replace_all_expanded=true
position_find_x=865
position_find_y=615
position_replace_x=855
position_replace_y=535
position_fif_x=675
position_fif_y=205

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;
